### PR TITLE
add a new API for request validation

### PR DESCRIPTION
**Pull request by wei-lee**
Adding a new API to call millicore for CSRF validation.

### CODE REVIEW

**Comment by grdryn** [comment]
@wei-lee Could you change [the Jenkins agent to 'nodejs6'](https://github.com/feedhenry/fh-millicore-client/blob/master/Jenkinsfile#L6)? That will allow the job to run. I don't know what happened to the nodejs4 one.

**Comment by wei-lee** [comment]
@grdryn will do. thanks.

**Review by camilamacedo86 — APPROVED** [review]
Perfect!

**Review by damienomurchu — APPROVED** [review]
Changes look good :+1:

**Pull request merged**
